version: "3.8"

services:
  tomcat-server:
    container_name: tomcat9
    image: tomcat:9.0
    volumes:
      - ./tomcat-users.xml:/usr/local/tomcat/config/tomcat-users.xml
    ports:
      - 8082:8080
  jenkins-server:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
     - 8866:8866
     - 50000:50000
    privileged: true
    environment:
      - JENKINS_OPTS='--httpPort=8866'